-- ----------------------------------------------------------------------------
-- 1. DIM_ENTITY (Geographical and Administrative Entities)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.dim_entity (
    entity_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_code         VARCHAR2(10 CHAR),
    entity_name         VARCHAR2(150 CHAR) NOT NULL,
    is_aggregate        NUMBER(1) DEFAULT ON NULL 0,
    created_at          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    
    CONSTRAINT uq_dim_entity_name UNIQUE (entity_name)
);

CREATE INDEX idx_dim_entity_code ON helios_core.dim_entity (entity_code);

COMMENT ON TABLE helios_core.dim_entity IS 'Dimension: Geographical entities including countries, continents, economic zones, and global aggregates';
COMMENT ON COLUMN helios_core.dim_entity.entity_id IS 'Surrogate primary key of the entity dimension';
COMMENT ON COLUMN helios_core.dim_entity.entity_code IS 'ISO-3 country code or regional identifier (e.g. POL, DEU, EU)';
COMMENT ON COLUMN helios_core.dim_entity.entity_name IS 'Full standard name of the country or regional entity';
COMMENT ON COLUMN helios_core.dim_entity.is_aggregate IS 'Flag indicating aggregate entity: 1 for regions/aggregates, 0 for sovereign countries';
COMMENT ON COLUMN helios_core.dim_entity.created_at IS 'Record creation timestamp in CORE';
COMMENT ON COLUMN helios_core.dim_entity.updated_at IS 'Record last update timestamp in CORE';


-- ----------------------------------------------------------------------------
-- 2. DIM_SERIES (Energy Sources, Fuels, and Breakdown Series)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.dim_series (
    series_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    series_name         VARCHAR2(100 CHAR) NOT NULL,
    series_category     VARCHAR2(50 CHAR),
    is_aggregate        NUMBER(1) DEFAULT ON NULL 0,
    created_at          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    updated_at          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    
    CONSTRAINT uq_dim_series_name UNIQUE (series_name)
);

CREATE INDEX idx_dim_series_cat ON helios_core.dim_series (series_category);

COMMENT ON TABLE helios_core.dim_series IS 'Dimension: Energy sources, fuel types, demand metrics, and emission series';
COMMENT ON COLUMN helios_core.dim_series.series_id IS 'Surrogate primary key of the series dimension';
COMMENT ON COLUMN helios_core.dim_series.series_name IS 'Standard name of the series (e.g. Solar, Wind, Coal, Total Generation)';
COMMENT ON COLUMN helios_core.dim_series.series_category IS 'High-level group: Renewables, Fossil, Clean, Demand, Emissions';
COMMENT ON COLUMN helios_core.dim_series.is_aggregate IS 'Flag indicating aggregate series: 1 for composite totals, 0 for discrete fuels';
COMMENT ON COLUMN helios_core.dim_series.created_at IS 'Record creation timestamp in CORE';
COMMENT ON COLUMN helios_core.dim_series.updated_at IS 'Record last update timestamp in CORE';


-- ----------------------------------------------------------------------------
-- 3. DIM_PERIOD (Time and Temporal Resolution Dimension)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.dim_period (
    period_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temporal_resolution VARCHAR2(20 CHAR) NOT NULL,
    raw_date            VARCHAR2(20 CHAR) NOT NULL,
    period_date         DATE NOT NULL,
    year_num            NUMBER(4) NOT NULL,
    month_num           NUMBER(2),
    quarter_num         NUMBER(1),
    period_label        VARCHAR2(50 CHAR) NOT NULL,
    created_at          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    
    CONSTRAINT uq_dim_period_grain UNIQUE (temporal_resolution, raw_date)
);

CREATE INDEX idx_dim_period_date ON helios_core.dim_period (period_date);
CREATE INDEX idx_dim_period_year ON helios_core.dim_period (year_num, month_num);

COMMENT ON TABLE helios_core.dim_period IS 'Dimension: Temporal resolution and calendar periods (yearly and monthly grains)';
COMMENT ON COLUMN helios_core.dim_period.period_id IS 'Surrogate primary key of the period dimension';
COMMENT ON COLUMN helios_core.dim_period.temporal_resolution IS 'Temporal grain: yearly or monthly';
COMMENT ON COLUMN helios_core.dim_period.raw_date IS 'Source date string format: YYYY for yearly, YYYY-MM for monthly';
COMMENT ON COLUMN helios_core.dim_period.period_date IS 'Normalized Oracle DATE (first calendar day of the given period)';
COMMENT ON COLUMN helios_core.dim_period.year_num IS 'Calendar year number (e.g. 2024)';
COMMENT ON COLUMN helios_core.dim_period.month_num IS 'Calendar month number (1-12 for monthly, NULL for yearly)';
COMMENT ON COLUMN helios_core.dim_period.quarter_num IS 'Calendar quarter number (1-4 for monthly, NULL for yearly)';
COMMENT ON COLUMN helios_core.dim_period.period_label IS 'Display label for UI charts and dashboards (e.g. 2024, Jan 2024)';
COMMENT ON COLUMN helios_core.dim_period.created_at IS 'Record creation timestamp in CORE';
