-- ----------------------------------------------------------------------------
-- 1. FACT_GENERATION (Electricity Generation)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.fact_generation (
    fact_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id               NUMBER NOT NULL,
    series_id               NUMBER NOT NULL,
    period_id               NUMBER NOT NULL,
    generation_twh          NUMBER(16, 6),
    share_of_generation_pct NUMBER(8, 4),
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR),
    
    CONSTRAINT fk_fact_gen_entity FOREIGN KEY (entity_id) REFERENCES helios_core.dim_entity (entity_id),
    CONSTRAINT fk_fact_gen_series FOREIGN KEY (series_id) REFERENCES helios_core.dim_series (series_id),
    CONSTRAINT fk_fact_gen_period FOREIGN KEY (period_id) REFERENCES helios_core.dim_period (period_id),
    CONSTRAINT uq_fact_gen_grain  UNIQUE (entity_id, series_id, period_id)
);

CREATE INDEX idx_fact_gen_entity ON helios_core.fact_generation (entity_id);
CREATE INDEX idx_fact_gen_series ON helios_core.fact_generation (series_id);
CREATE INDEX idx_fact_gen_period ON helios_core.fact_generation (period_id);

COMMENT ON TABLE helios_core.fact_generation IS 'Fact: Monthly and yearly electricity generation volumes and fuel mix shares';
COMMENT ON COLUMN helios_core.fact_generation.fact_id IS 'Surrogate identity primary key';
COMMENT ON COLUMN helios_core.fact_generation.entity_id IS 'Foreign key to DIM_ENTITY';
COMMENT ON COLUMN helios_core.fact_generation.series_id IS 'Foreign key to DIM_SERIES';
COMMENT ON COLUMN helios_core.fact_generation.period_id IS 'Foreign key to DIM_PERIOD';
COMMENT ON COLUMN helios_core.fact_generation.generation_twh IS 'Electricity generation in Terawatt-hours (TWh)';
COMMENT ON COLUMN helios_core.fact_generation.share_of_generation_pct IS 'Share of generation in percent (%)';
COMMENT ON COLUMN helios_core.fact_generation.load_timestamp IS 'Timestamp when fact row was loaded';
COMMENT ON COLUMN helios_core.fact_generation.source_file IS 'Source data lake URI for lineage tracking';


-- ----------------------------------------------------------------------------
-- 2. FACT_CAPACITY (Installed Capacity)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.fact_capacity (
    fact_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id               NUMBER NOT NULL,
    series_id               NUMBER NOT NULL,
    period_id               NUMBER NOT NULL,
    capacity_gw             NUMBER(16, 6),
    capacity_w_per_capita   NUMBER(16, 6),
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR),
    
    CONSTRAINT fk_fact_cap_entity FOREIGN KEY (entity_id) REFERENCES helios_core.dim_entity (entity_id),
    CONSTRAINT fk_fact_cap_series FOREIGN KEY (series_id) REFERENCES helios_core.dim_series (series_id),
    CONSTRAINT fk_fact_cap_period FOREIGN KEY (period_id) REFERENCES helios_core.dim_period (period_id),
    CONSTRAINT uq_fact_cap_grain  UNIQUE (entity_id, series_id, period_id)
);

CREATE INDEX idx_fact_cap_entity ON helios_core.fact_capacity (entity_id);
CREATE INDEX idx_fact_cap_series ON helios_core.fact_capacity (series_id);
CREATE INDEX idx_fact_cap_period ON helios_core.fact_capacity (period_id);

COMMENT ON TABLE helios_core.fact_capacity IS 'Fact: Monthly installed renewable capacity (solar, wind) in GW and W/capita';
COMMENT ON COLUMN helios_core.fact_capacity.fact_id IS 'Surrogate identity primary key';
COMMENT ON COLUMN helios_core.fact_capacity.entity_id IS 'Foreign key to DIM_ENTITY';
COMMENT ON COLUMN helios_core.fact_capacity.series_id IS 'Foreign key to DIM_SERIES';
COMMENT ON COLUMN helios_core.fact_capacity.period_id IS 'Foreign key to DIM_PERIOD';
COMMENT ON COLUMN helios_core.fact_capacity.capacity_gw IS 'Installed capacity in Gigawatts (GW)';
COMMENT ON COLUMN helios_core.fact_capacity.capacity_w_per_capita IS 'Installed capacity in Watts per capita';
COMMENT ON COLUMN helios_core.fact_capacity.load_timestamp IS 'Timestamp when fact row was loaded';
COMMENT ON COLUMN helios_core.fact_capacity.source_file IS 'Source data lake URI for lineage tracking';


-- ----------------------------------------------------------------------------
-- 3. FACT_CARBON_INTENSITY (Grid Emissions Intensity)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.fact_carbon_intensity (
    fact_id                          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id                        NUMBER NOT NULL,
    period_id                        NUMBER NOT NULL,
    emissions_intensity_gco2_per_kwh NUMBER(16, 6),
    load_timestamp                   TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file                      VARCHAR2(500 CHAR),
    
    CONSTRAINT fk_fact_ci_entity FOREIGN KEY (entity_id) REFERENCES helios_core.dim_entity (entity_id),
    CONSTRAINT fk_fact_ci_period FOREIGN KEY (period_id) REFERENCES helios_core.dim_period (period_id),
    CONSTRAINT uq_fact_ci_grain  UNIQUE (entity_id, period_id)
);

CREATE INDEX idx_fact_ci_entity ON helios_core.fact_carbon_intensity (entity_id);
CREATE INDEX idx_fact_ci_period ON helios_core.fact_carbon_intensity (period_id);

COMMENT ON TABLE helios_core.fact_carbon_intensity IS 'Fact: Monthly and yearly grid carbon intensity (gCO2/kWh)';
COMMENT ON COLUMN helios_core.fact_carbon_intensity.fact_id IS 'Surrogate identity primary key';
COMMENT ON COLUMN helios_core.fact_carbon_intensity.entity_id IS 'Foreign key to DIM_ENTITY';
COMMENT ON COLUMN helios_core.fact_carbon_intensity.period_id IS 'Foreign key to DIM_PERIOD';
COMMENT ON COLUMN helios_core.fact_carbon_intensity.emissions_intensity_gco2_per_kwh IS 'Grid carbon intensity in gCO2/kWh';
COMMENT ON COLUMN helios_core.fact_carbon_intensity.load_timestamp IS 'Timestamp when fact row was loaded';
COMMENT ON COLUMN helios_core.fact_carbon_intensity.source_file IS 'Source data lake URI for lineage tracking';


-- ----------------------------------------------------------------------------
-- 4. FACT_DEMAND (Electricity Consumption and Demand)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.fact_demand (
    fact_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id               NUMBER NOT NULL,
    period_id               NUMBER NOT NULL,
    demand_twh              NUMBER(16, 6),
    demand_mwh_per_capita   NUMBER(16, 6),
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR),
    
    CONSTRAINT fk_fact_dem_entity FOREIGN KEY (entity_id) REFERENCES helios_core.dim_entity (entity_id),
    CONSTRAINT fk_fact_dem_period FOREIGN KEY (period_id) REFERENCES helios_core.dim_period (period_id),
    CONSTRAINT uq_fact_dem_grain  UNIQUE (entity_id, period_id)
);

CREATE INDEX idx_fact_dem_entity ON helios_core.fact_demand (entity_id);
CREATE INDEX idx_fact_dem_period ON helios_core.fact_demand (period_id);

COMMENT ON TABLE helios_core.fact_demand IS 'Fact: Monthly electricity demand and per capita consumption';
COMMENT ON COLUMN helios_core.fact_demand.fact_id IS 'Surrogate identity primary key';
COMMENT ON COLUMN helios_core.fact_demand.entity_id IS 'Foreign key to DIM_ENTITY';
COMMENT ON COLUMN helios_core.fact_demand.period_id IS 'Foreign key to DIM_PERIOD';
COMMENT ON COLUMN helios_core.fact_demand.demand_twh IS 'Electricity demand in Terawatt-hours (TWh)';
COMMENT ON COLUMN helios_core.fact_demand.demand_mwh_per_capita IS 'Electricity demand in Megawatt-hours (MWh) per capita';
COMMENT ON COLUMN helios_core.fact_demand.load_timestamp IS 'Timestamp when fact row was loaded';
COMMENT ON COLUMN helios_core.fact_demand.source_file IS 'Source data lake URI for lineage tracking';


-- ----------------------------------------------------------------------------
-- 5. FACT_EMISSIONS (Power Sector Emissions)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_core.fact_emissions (
    fact_id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_id               NUMBER NOT NULL,
    series_id               NUMBER NOT NULL,
    period_id               NUMBER NOT NULL,
    emissions_mtco2         NUMBER(16, 6),
    share_of_emissions_pct  NUMBER(8, 4),
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR),
    
    CONSTRAINT fk_fact_em_entity FOREIGN KEY (entity_id) REFERENCES helios_core.dim_entity (entity_id),
    CONSTRAINT fk_fact_em_series FOREIGN KEY (series_id) REFERENCES helios_core.dim_series (series_id),
    CONSTRAINT fk_fact_em_period FOREIGN KEY (period_id) REFERENCES helios_core.dim_period (period_id),
    CONSTRAINT uq_fact_em_grain  UNIQUE (entity_id, series_id, period_id)
);

CREATE INDEX idx_fact_em_entity ON helios_core.fact_emissions (entity_id);
CREATE INDEX idx_fact_em_series ON helios_core.fact_emissions (series_id);
CREATE INDEX idx_fact_em_period ON helios_core.fact_emissions (period_id);

COMMENT ON TABLE helios_core.fact_emissions IS 'Fact: Monthly and yearly power sector greenhouse gas emissions and shares';
COMMENT ON COLUMN helios_core.fact_emissions.fact_id IS 'Surrogate identity primary key';
COMMENT ON COLUMN helios_core.fact_emissions.entity_id IS 'Foreign key to DIM_ENTITY';
COMMENT ON COLUMN helios_core.fact_emissions.series_id IS 'Foreign key to DIM_SERIES';
COMMENT ON COLUMN helios_core.fact_emissions.period_id IS 'Foreign key to DIM_PERIOD';
COMMENT ON COLUMN helios_core.fact_emissions.emissions_mtco2 IS 'Emissions in Million tonnes of CO2 (MtCO2)';
COMMENT ON COLUMN helios_core.fact_emissions.share_of_emissions_pct IS 'Share of total power sector emissions in percent (%)';
COMMENT ON COLUMN helios_core.fact_emissions.load_timestamp IS 'Timestamp when fact row was loaded';
COMMENT ON COLUMN helios_core.fact_emissions.source_file IS 'Source data lake URI for lineage tracking';


