-- ============================================================================
-- HELIOS DATA PLATFORM - STAGING LAYER (STG)
-- Script: sql/01_stg/01_staging_tables.sql
-- Target Schema: HELIOS_STG
-- Description: Landing tables for raw ingestion from Ember Energy API v1.
--              Standards: Explicit CHAR length semantics and DEFAULT ON NULL.
--              Note: DEFAULT ON NULL implicitly enforces a NOT NULL constraint.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. STG_EMBER_GENERATION (Electricity Generation & Fuel Mix)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_stg.stg_ember_generation (
    stg_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR) NOT NULL,
    temporal_resolution     VARCHAR2(20 CHAR) NOT NULL,
    stg_status              VARCHAR2(20 CHAR) DEFAULT ON NULL 'NEW',
    error_message           VARCHAR2(1000 CHAR),
    
    entity                  VARCHAR2(150 CHAR),
    entity_code             VARCHAR2(10 CHAR),
    is_aggregate_entity     NUMBER(1),
    raw_date                VARCHAR2(20 CHAR),
    series                  VARCHAR2(100 CHAR),
    is_aggregate_series     NUMBER(1),
    generation_twh          NUMBER(16, 6),
    share_of_generation_pct NUMBER(8, 4)
);

CREATE INDEX idx_stg_gen_status ON helios_stg.stg_ember_generation (stg_status);

COMMENT ON TABLE helios_stg.stg_ember_generation IS 'Staging: Electricity generation and energy mix breakdown from Ember API';
COMMENT ON COLUMN helios_stg.stg_ember_generation.stg_id IS 'Surrogate identity primary key for staging row tracking';
COMMENT ON COLUMN helios_stg.stg_ember_generation.load_timestamp IS 'Timestamp when the row was ingested into staging';
COMMENT ON COLUMN helios_stg.stg_ember_generation.source_file IS 'Source file path, cloud URI (e.g. gs://, s3://, oci://), or object storage key from Bronze Data Lake';
COMMENT ON COLUMN helios_stg.stg_ember_generation.temporal_resolution IS 'Temporal grain: yearly or monthly';
COMMENT ON COLUMN helios_stg.stg_ember_generation.stg_status IS 'Processing status flag: NEW, PROCESSED, ERROR';
COMMENT ON COLUMN helios_stg.stg_ember_generation.error_message IS 'Validation or ETL error message if processing failed';
COMMENT ON COLUMN helios_stg.stg_ember_generation.entity IS 'Country or region name';
COMMENT ON COLUMN helios_stg.stg_ember_generation.entity_code IS 'ISO-3 country code (e.g. POL, DEU)';
COMMENT ON COLUMN helios_stg.stg_ember_generation.raw_date IS 'Raw date string from source (e.g. 2023 or 2023-01)';
COMMENT ON COLUMN helios_stg.stg_ember_generation.series IS 'Electricity generation fuel/source (e.g. Solar, Wind, Coal)';
COMMENT ON COLUMN helios_stg.stg_ember_generation.generation_twh IS 'Electricity generation volume in Terawatt-hours (TWh)';
COMMENT ON COLUMN helios_stg.stg_ember_generation.share_of_generation_pct IS 'Share of total generation mix in percent (%)';


-- ----------------------------------------------------------------------------
-- 2. STG_EMBER_CAPACITY (Installed Capacity - Wind and Solar)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_stg.stg_ember_capacity (
    stg_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR) NOT NULL,
    temporal_resolution     VARCHAR2(20 CHAR) NOT NULL,
    stg_status              VARCHAR2(20 CHAR) DEFAULT ON NULL 'NEW',
    error_message           VARCHAR2(1000 CHAR),
    
    entity                  VARCHAR2(150 CHAR),
    entity_code             VARCHAR2(10 CHAR),
    is_aggregate_entity     NUMBER(1),
    raw_date                VARCHAR2(20 CHAR),
    series                  VARCHAR2(100 CHAR),
    is_aggregate_series     NUMBER(1),
    capacity_gw             NUMBER(16, 6),
    capacity_w_per_capita   NUMBER(16, 6)
);

CREATE INDEX idx_stg_cap_status ON helios_stg.stg_ember_capacity (stg_status);

COMMENT ON TABLE helios_stg.stg_ember_capacity IS 'Staging: Installed wind and solar renewable capacity from Ember API';
COMMENT ON COLUMN helios_stg.stg_ember_capacity.stg_id IS 'Surrogate identity primary key for staging row tracking';
COMMENT ON COLUMN helios_stg.stg_ember_capacity.source_file IS 'Source file path, cloud URI (e.g. gs://, s3://, oci://), or object storage key from Bronze Data Lake';
COMMENT ON COLUMN helios_stg.stg_ember_capacity.temporal_resolution IS 'Temporal grain: monthly';
COMMENT ON COLUMN helios_stg.stg_ember_capacity.capacity_gw IS 'Installed capacity in Gigawatts (GW)';
COMMENT ON COLUMN helios_stg.stg_ember_capacity.capacity_w_per_capita IS 'Installed capacity in Watts per capita';


-- ----------------------------------------------------------------------------
-- 3. STG_EMBER_CARBON_INTENSITY (Grid Carbon Intensity)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_stg.stg_ember_carbon_intensity (
    stg_id                           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_timestamp                   TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file                      VARCHAR2(500 CHAR) NOT NULL,
    temporal_resolution              VARCHAR2(20 CHAR) NOT NULL,
    stg_status                       VARCHAR2(20 CHAR) DEFAULT ON NULL 'NEW',
    error_message                    VARCHAR2(1000 CHAR),
    
    entity                           VARCHAR2(150 CHAR),
    entity_code                      VARCHAR2(10 CHAR),
    is_aggregate_entity              NUMBER(1),
    raw_date                         VARCHAR2(20 CHAR),
    emissions_intensity_gco2_per_kwh NUMBER(16, 6)
);

CREATE INDEX idx_stg_ci_status ON helios_stg.stg_ember_carbon_intensity (stg_status);

COMMENT ON TABLE helios_stg.stg_ember_carbon_intensity IS 'Staging: Grid carbon emissions intensity from Ember API';
COMMENT ON COLUMN helios_stg.stg_ember_carbon_intensity.stg_id IS 'Surrogate identity primary key for staging row tracking';
COMMENT ON COLUMN helios_stg.stg_ember_carbon_intensity.source_file IS 'Source file path, cloud URI (e.g. gs://, s3://, oci://), or object storage key from Bronze Data Lake';
COMMENT ON COLUMN helios_stg.stg_ember_carbon_intensity.emissions_intensity_gco2_per_kwh IS 'Grid emissions intensity in grams CO2 equivalent per kWh';


-- ----------------------------------------------------------------------------
-- 4. STG_EMBER_DEMAND (Electricity Demand / Consumption)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_stg.stg_ember_demand (
    stg_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR) NOT NULL,
    temporal_resolution     VARCHAR2(20 CHAR) NOT NULL,
    stg_status              VARCHAR2(20 CHAR) DEFAULT ON NULL 'NEW',
    error_message           VARCHAR2(1000 CHAR),
    
    entity                  VARCHAR2(150 CHAR),
    entity_code             VARCHAR2(10 CHAR),
    is_aggregate_entity     NUMBER(1),
    raw_date                VARCHAR2(20 CHAR),
    demand_twh              NUMBER(16, 6),
    demand_mwh_per_capita   NUMBER(16, 6)
);

CREATE INDEX idx_stg_dem_status ON helios_stg.stg_ember_demand (stg_status);

COMMENT ON TABLE helios_stg.stg_ember_demand IS 'Staging: Electricity demand and consumption from Ember API';
COMMENT ON COLUMN helios_stg.stg_ember_demand.stg_id IS 'Surrogate identity primary key for staging row tracking';
COMMENT ON COLUMN helios_stg.stg_ember_demand.source_file IS 'Source file path, cloud URI (e.g. gs://, s3://, oci://), or object storage key from Bronze Data Lake';
COMMENT ON COLUMN helios_stg.stg_ember_demand.demand_twh IS 'Total electricity demand in Terawatt-hours (TWh)';
COMMENT ON COLUMN helios_stg.stg_ember_demand.demand_mwh_per_capita IS 'Electricity demand in Megawatt-hours (MWh) per capita';


-- ----------------------------------------------------------------------------
-- 5. STG_EMBER_EMISSIONS (Power Sector Emissions)
-- ----------------------------------------------------------------------------
CREATE TABLE helios_stg.stg_ember_emissions (
    stg_id                  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    load_timestamp          TIMESTAMP DEFAULT ON NULL SYSTIMESTAMP,
    source_file             VARCHAR2(500 CHAR) NOT NULL,
    temporal_resolution     VARCHAR2(20 CHAR) NOT NULL,
    stg_status              VARCHAR2(20 CHAR) DEFAULT ON NULL 'NEW',
    error_message           VARCHAR2(1000 CHAR),
    
    entity                  VARCHAR2(150 CHAR),
    entity_code             VARCHAR2(10 CHAR),
    is_aggregate_entity     NUMBER(1),
    raw_date                VARCHAR2(20 CHAR),
    series                  VARCHAR2(100 CHAR),
    is_aggregate_series     NUMBER(1),
    emissions_mtco2         NUMBER(16, 6),
    share_of_emissions_pct  NUMBER(8, 4)
);

CREATE INDEX idx_stg_em_status ON helios_stg.stg_ember_emissions (stg_status);

COMMENT ON TABLE helios_stg.stg_ember_emissions IS 'Staging: Power sector greenhouse gas emissions from Ember API';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.stg_id IS 'Surrogate identity primary key for staging row tracking';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.source_file IS 'Source file path, cloud URI (e.g. gs://, s3://, oci://), or object storage key from Bronze Data Lake';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.temporal_resolution IS 'Temporal resolution of the emissions data (e.g., annual, monthly)';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.stg_status IS 'Staging row status (e.g., NEW, PROCESSED)';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.error_message IS 'Error message if the row failed processing';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.entity IS 'Name of the entity (e.g., country, region) for which emissions are reported';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.entity_code IS 'Code of the entity (e.g., ISO country code)';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.is_aggregate_entity IS 'Flag indicating if the entity represents an aggregate (1 for true, 0 for false)';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.raw_date IS 'Raw date string as provided by the source';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.series IS 'Name of the emissions series';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.is_aggregate_series IS 'Flag indicating if the series represents an aggregate (1 for true, 0 for false)';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.emissions_mtco2 IS 'Total emissions in Million tonnes of CO2 (MtCO2)';
COMMENT ON COLUMN helios_stg.stg_ember_emissions.share_of_emissions_pct IS 'Share of total power sector emissions in percent (%)';
